name: CD Production

on:
  push:
    branches: [release]

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: production
    secrets: inherit
