name: CD Staging

on:
  push:
    branches: [staging]

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yaml
    with:
      environment: staging
    secrets: inherit
